services:
  postgres:
    image: postgres:16
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-root}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-root}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    ports:
      - ${POSTGRES_PORT:-5432}:5432
  localstack:
    image: localstack/localstack:latest
    restart: always
    environment:
      SERVICES: s3
    ports:
      - 4566:4566
    volumes:
      - ./localstack-script.sh:/etc/localstack/init/ready.d/script.sh
      - "/var/run/docker.sock:/var/run/docker.sock"
  # Uncomment below to simulate Azure Blob Storage (don't forget to run the init_azure_storage.py to create the container)
  # azurite:
  #   image: mcr.microsoft.com/azure-storage/azurite
  #   ports:
  #     - "10000:10000"  # Blob service
  #     - "10001:10001"  # Queue service
  #     - "10002:10002"  # Table service
  #   volumes:
  #     - ./.data/azurite:/data
  #   command: "azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0"